from .auth_routers import auth_bp
from .recommendation_routes import rec_bp
from .category_routes import category_bp
from .topic_routes import topic_bp
from .level_routes import level_bp
from .resource_routes import resource_bp
from .interaction_routes import interaction_bp
from .test_routes import test_bp
from .knowledge_profile_routes import profile_bp
from .recommendation_history_routes import recommendation_history_bp
